import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ReduxProviderWrapper from '@/lib/store/ReduxProviderWrapper';
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Linkedin", // đổi title
  description: "Generated by create next app",
  icons: {
    icon: "/linkedin-logo.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <ReduxProviderWrapper>{children}</ReduxProviderWrapper>
        {/* Toast container toàn cục */}
        <ToastContainer position="top-center" autoClose={3000} />
      </body>
    </html>
  );
}
